import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <div className='banner__wrapper bg-black text-5xl w-screen'>
        <div className='banner'>
          <p className='text-white'>ciao</p>
          <p className='text-white'>ciao</p>
          <p className='text-white'>ciao</p>
          <p className='text-white'>ciao</p>
          <p className='text-white'>ciao</p>
          <p className='text-white'>ciao</p>
          <p className='text-white'>ciao</p>
          <p className='text-white'>ciao</p>
        </div>

        <div className='banner banner2'>
          <div className='flex gap-[10vw]'>
            <p className='text-white'>ciao</p>
            <p className='text-white'>ciao</p>
            <p className='text-white'>ciao</p>
            <p className='text-white'>ciao</p>
            <p className='text-white'>ciao</p>
            <p className='text-white'>ciao</p>
            <p className='text-white'>ciao</p>
            <p className='text-white'>ciao</p>
          </div>
        </div>

      </div>

      <p>Nam nec egestas arcu. Phasellus aliquam molestie imperdiet. Duis consectetur enim vitae tellus faucibus ultricies. Aenean mauris era

      </p>

      <div className='sticky  h-[300vh]'>
        <div className='relative'>
          <div className='sticky left-0 top-[100px]'><Image layout='responsive' width={16} height={9} objectFit={'cover'} src="https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="" /></div>
          <div className='sticky left-0 top-[100px]'><Image layout='responsive' width={16} height={9} objectFit={'cover'} src="https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="" /></div>
          <div className='sticky left-0 top-[100px]'><Image layout='responsive' width={16} height={9} objectFit={'cover'} src="https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80" alt="" /></div>
        </div>
      </div>

      <br />


      <p>Nam nec egestas arcu. Phasellus aliquam molestie imperdiet. Duis consectetur enim vitae tellus faucibus ultricies. Aenean mauris erat, tincidunt in felis sed, dignissim consequat tortor. Praesent fringilla velit volutpat nisi pellentesque, et imperdiet justo elementum. Morbi sagittis velit tristique sapien posuere congue. Nullam elementum auctor ullamcorper. Nunc gravida libero eu ligula tempus iaculis.

      </p>


      <p>Nam nec egestas arcu. Phasellus aliquam molestie imperdiet. Duis consectetur enim vitae tellus faucibus ultricies. Aenean mauris erat, tincidunt in felis sed, dignissim consequat tortor. Praesent fringilla velit volutpat nisi pellentesque, et imperdiet justo elementum. Morbi sagittis velit tristique sapien posuere congue. Nullam elementum auctor ullamcorper. Nunc gravida libero eu ligula tempus iaculis.

      </p>
      <p>Nam nec egestas arcu. Phasellus aliquam molestie imperdiet. Duis consectetur enim vitae tellus faucibus ultricies. Aenean mauris erat, tincidunt in felis sed, dignissim consequat tortor. Praesent fringilla velit volutpat nisi pellentesque, et imperdiet justo elementum. Morbi sagittis velit tristique sapien posuere congue. Nullam elementum auctor ullamcorper. Nunc gravida libero eu ligula tempus iaculis.

      </p>

      <p>Nam nec egestas arcu. Phasellus aliquam molestie imperdiet. Duis consectetur enim vitae tellus faucibus ultricies. Aenean mauris erat, tincidunt in felis sed, dignissim consequat tortor. Praesent fringilla velit volutpat nisi pellentesque, et imperdiet justo elementum. Morbi sagittis velit tristique sapien posuere congue. Nullam elementum auctor ullamcorper. Nunc gravida libero eu ligula tempus iaculis.

      </p>
      <p>Nam nec egestas arcu. Phasellus aliquam molestie imperdiet. Duis consectetur enim vitae tellus faucibus ultricies. Aenean mauris erat, tincidunt in felis sed, dignissim consequat tortor. Praesent fringilla velit volutpat nisi pellentesque, et imperdiet justo elementum. Morbi sagittis velit tristique sapien posuere congue. Nullam elementum auctor ullamcorper. Nunc gravida libero eu ligula tempus iaculis.

      </p>

      <p>Nam nec egestas arcu. Phasellus aliquam molestie imperdiet. Duis consectetur enim vitae tellus faucibus ultricies. Aenean mauris erat, tincidunt in felis sed, dignissim consequat tortor. Praesent fringilla velit volutpat nisi pellentesque, et imperdiet justo elementum. Morbi sagittis velit tristique sapien posuere congue. Nullam elementum auctor ullamcorper. Nunc gravida libero eu ligula tempus iaculis.

      </p>
      <p>Nam nec egestas arcu. Phasellus aliquam molestie imperdiet. Duis consectetur enim vitae tellus faucibus ultricies. Aenean mauris erat, tincidunt in felis sed, dignissim consequat tortor. Praesent fringilla velit volutpat nisi pellentesque, et imperdiet justo elementum. Morbi sagittis velit tristique sapien posuere congue. Nullam elementum auctor ullamcorper. Nunc gravida libero eu ligula tempus iaculis.

      </p>
    </div>
  )
}
